source :rubygems

group :dev do
  # development environment gems
end

group :test do
  # testing environment gems
end

group :prod do
  # production environment gems
end

gem 'e', :path => '/somebit/projects/personal/Ruby/Gems/espresso'
gem 'thin'
gem 'sprockets'
