require 'fileutils'
require 'erb'
require 'rubygems'
require 'tilt'

require 'e-core'

require 'e-more/init'
require 'e-more/view/base'
require 'e-more/view/e_app'
require 'e-more/view/setup'
require 'e-more/assets/base'
require 'e-more/assets/e_app'
require 'e-more/cache'
require 'e-more/crud'
require 'e-more/ipcm'
