source :rubygems

group :development do
  # development environment gems
end

group :test do
  # testing environment gems
end

group :production do
  # production environment gems
end

gem 'e'
gem 'thin'
gem 'sprockets'
