require 'yaml'
require 'logger'

require 'e-more/generator/init'
require 'e-more/generator/helpers'
require 'e-more/generator/generate_project'
require 'e-more/generator/generate_controller'
require 'e-more/generator/generate_route'
require 'e-more/generator/generate_view'
require 'e-more/generator/generate_model'
